#Connfigures blueteaam centos networking
- name: centos-networking
  hosts: centos_server
  tasks:
    - name: centos_server
      hostname:
        name: "{{hostname}}"
      become: yes
    
    - name: add host to hosts file
      lineinfile:
        path: /etc/hosts
        line: '127.0.1.1   {{hostname}}'
      become: yes 
    
    - name: push over the networking scripts
      template:
        src: files/centos/ifcfg-script.j2
        dest: '/etc/sysconfig/network-scripts/ifcfg-{{device}}'
        mode: 0644
        owner: root
        group: root
        force: yes
      become: yes
    
    - name: restart networking
      shell: "sleep 5 && reboot"
      become: yes
      async: 1
      poll: 0