#Create OU
- name: Create a Blue Team DC
  hosts: domain_controller
  gather_facts: no
  tasks:
    - name: load from jinja
      win_template:
        src: files/windows/create-ou.ps1.j2
        dest: C:\480\create-ou.ps1
    - name: run the script
      async: 10
      poll: 0
      win_shell:
        C:\480\create-ou.ps1

        