#Playbook configures a static map to your fw
- name: vyos
  hosts: vyos
  vars_prompt:
    - name: mapped_ip
      prompt: What IP do you want static mapped
      private: no
    - name: mapped_mac
      prompt: What is the host MAC
      private: no
  tasks:
    - name: Show configuration on ethernet devices eth0 and eth1
      vyos_config:
        lines:
        - "set service dhcp-server shared-network-name {{shared_network_name}} subnet {{dhcp_subnet}} static-mapping {{static_map_name}} ip-address  {{ mapped_ip }}"
        - "set service dhcp-server shared-network-name {{shared_network_name}} subnet {{dhcp_subnet}} static-mapping {{static_map_name}} mac-address  {{ mapped_mac }}"
