#Playbook configures RDP
- name: windows-RDP
  hosts: windows_workstation
  gather_facts: no
  tasks:
    - name: create a deploy directory
      win_file:
        path: C:\480
        state: directory
    - name: load from j inja
      win_template:
        src: files/windows/rdp.ps1.j2
        dest: C:\480\rdp.ps1
    - name: run the script
      async: 10
      poll: 0
      win_shell:
        C:\480\rdp.ps1



        